# Generated by Django 2.2.3 on 2019-07-14 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('non_auth_user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'admin_block'), (2, 'non_auth_block_request')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocked_ips',
                'verbose_name_plural': 'Blocked IPs',
                'verbose_name': 'Blocked IP',
                'ordering': ['-id'],
            },
        ),
    ]
